version: '3'
services:
  client:
    image: client/yasp:v1
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules/
      - /app/build/
      - .:/app
    links:
      - server
  server:
    image: server/yasp:v1
    build:
      context: ./server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'
    links:
      - mongo
      - redis
    env_file:
      - ./server/.env
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
