version: '3'
services:
  server:
    image: server/yasp:v1
    build:
      context: . #server
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
      # - ./server:/app
    ports:
      - '5000:5000'
    links:
      - mongo
      - redis
    env_file:
      - .env
  # tests:
  #   build:
  #     dockerfile: Dockerfile
  #     context: . #server
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #     - ./server:/app
  #   links:
  #     - mongo
  #     - redis
  #   command: ['npm', 'run', 'test-watch']
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
